### ISSUE TITLE
What driver should we use?

### ISSUE THREAD

**Issue by kmckee** [page-object-js/page-object-js#5]
I've been looking into this a little more, and it looks like we have two viable options:

http://webdriver.io/

or

http://zombie.js.org/

Both are being actively developed.  Zombiejs appears to be more popular, but it doesn't look like they support a native context.  So we wouldn't be able to support hybrid functionality if we went with it.

Eventually we could always support both.  But where to start?

**Comment by kwpeters** [comment]
I don't have much experience in this area, so I'm afraid that I don't have much of an opinion.  I just have one question.  It looks like Zombie is its own (headless) web browser, similar to PhantomJS.  I've heard criticisms of using PhantomJS in the past because it is not the _real thing_.  Some say that if your users are going to be running on Chrome, Firefox, IE, Safari, etc., then that's what your tests need to run on too.  It really doesn't matter if your tests pass on PhantomJS, but your software fails on Chrome.  Could the same be said for Zombie?

**Comment by yaworsw** [comment]
start with https://github.com/admc/wd then write adapters for other drivers?

**Comment by kmckee** [comment]
That admc/wd driver hasn't had a single commit in over a year.  Seems to be abandoned.

I've been trying to get webdriver.io to work.  It has very active development and a gitter chat where people have been answering my questions.  I'm leaning that way.

Wasn't there a reason we couldn't use webdriver.io at work, though?

**Comment by kmckee** [comment]
oh, wait, it's only been 3 months since admc/wd has had a commit.  That's not that bad.

**Comment by yaworsw** [comment]
As of last August wdio did not work with appium But Ed did

**Comment by kmckee** [comment]
I swear I read somewhere that it was being abandoned in favor of webdriverio but I can't find it anymore

**Comment by YashdalfTheGray** [comment]
This is new ground for me too so I don't really have an opinion. I would lean towards webdriver.io since it looks like it's active and the code seems simple; although I recognize that trying to get it to work has been non-trivial but that could just be our unfamiliarity with webdriver? LIke I said, I'm (not even) a novice here so don't count this as an opinion, just me trying to participate. :smile: 

As for the appium incompatibility, we can start at webdriver.io (to get a good base) and then impement support for others?

**Comment by kmckee** [comment]
Found this guy and had a pretty easy time getting it set up (relative to the other options).
https://github.com/SeleniumHQ/selenium
http://seleniumhq.github.io/selenium/docs/api/javascript/

**Comment by kmckee** [comment]
Lets stick with the one that's on master now and pivot if we need to.
